name: Daily Workflow at 7 AM Beijing Time

on:
  schedule:
    - cron: '0 23 * * *'  # Runs at 23:00 UTC, which is 7:00 AM Beijing Time

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install arxiv  # Replace with your actual dependencies

    - name: Execute script
      run: python your_script.py  # Replace with your actual script

    - name: Commit and push if changed
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add README.md
        git commit -m "Update README.md with latest arXiv papers" -a || echo "No changes to commit"
        git push --force 
